version: '3.8'

services:
  # OpenTelemetry Collector
  otel:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-config.yaml"]
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8888:8888"   # Prometheus metrics
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # Health check
    depends_on:
      - jaeger

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"  # UI
      - "14250:14250"  # Model/collector gRPC
      - "14268:14268"  # Collector HTTP
      - "6831:6831/udp"  # Thrift compact
      - "6832:6832/udp"  # Thrift binary
      #- "4317:4317"    # OTLP gRPC
      #- "4318:4318"    # OTLP HTTP

  # Test trace generator
  tracegen:
    image: jaegertracing/jaeger-tracegen
    depends_on:
      - otel
    command: [
      "-service", "test-service",
      "-traces", "10",
      "-collector", "http://otel:4318"
    ]
